import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/utils/Contexts";
import { CartProvider } from "@/utils/CartContext";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "My Next.js Site",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            <Navbar/>
              {children}
            <Footer/>
          </CartProvider>
        </AuthProvider>
        </body>
    </html>
  )
}